SELECT *
FROM customer;

-- What is the Total Revenue generated by male v/s female customers?

Select gender,sum(purchase_amount) as total_revenue
from customer
group by gender
order by total_revenue desc ;

-- Which customer used a discount but still spent more than avg purchase amount?
select customer_id , purchase_amount 
from customer
where purchase_amount >= (select avg(purchase_amount) from customer);

-- which are the top 5 products with the highest average review rating?
Select item_purchased as Top_5_Products, round(avg(review_rating::numeric),2) as Rating
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Compare the avg purchase amount between standard and express shipping?
select shipping_type , round(avg(purchase_amount),2) as purchase_amount
from customer
where shipping_type in ('Standard' , 'Express')
group by shipping_type 
order by purchase_amount desc;

-- Do Subscribed customers spend more? Compare avg spend and total revenue b/w sub or non-sub?
select subscription_status , count(customer_id) as total_customers , round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue desc;

-- which 5 products have the highest percentage of pruchases with disount applied?
select item_purchased as products ,
round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- Segment customer into New,Returning and loyal based on their total
-- no. of previous purchases and show the count at each segment?

with customer_type as (
select customer_id , previous_purchases,
case
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer
)

select customer_segment, count(*) as No_of_customers
from customer_type
group by customer_segment
order by No_of_customers desc;

-- what are the top 3 most purchased products within each category?
with item_counts as(
select category, item_purchased, count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category ,item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

-- Are customers who are repeat buyers (more than 5 previous purchases ) are also likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status
order by repeat_buyers desc;

-- what is the revenue contribution of each age group
select age_group , round(sum(purchase_amount),2) as total_revenue
from customer
group by age_group
order by total_revenue desc

